bugfix/csp bug e mais uns
Daguje/hand-mouse-extension pull request #6
Opened 2023-05-13 20:10 UTC by souzjfe

- patchon
- chore: adiciona deteccao de maos em loop
- feat: (wip) adicionado desenho das maos
- fix: width do canvas das maos
- fix: alterado framerate da camera
- chore: primeira versão sem tailwind - 🔧
- chore: configurando tailwind e daisyui - 🔧
- chore: add alias - 🔧
- chore: troca de mensagens entr os servicos - 🔧
- chore: ate aqui ta funcionando - 🔧
- ci: nova estrutura e config do webpack - 👷‍♂
- chore: configuração para troca de mensagens - 🔧

2023-05-14 01:58 UTC, danielg-favero requested changes

2023-05-14 01:58 UTC, danielg-favero commented on src/pages/options/index.ts
> +  let browserName = 'No browser detection';
O correto não seria 'No browser detected'?

2023-05-14 01:58 UTC, danielg-favero commented on src/pages/options/options.html
> +    <h1>Options pagssse ss!</h1>
Não sei se é a intenção, mas esse title poderia mudar kkkk

2023-05-14 01:58 UTC, danielg-favero commented on src/utils/InitializeElementByStorage/index.ts
> +export function initializeInputByStorage(element: HTMLInputElement) {
Um nome melhor para esse método poderia ser "setInputValueFromStorage"

2023-05-19 22:20 UTC, Gugonunes requested changes
Bom PR mano 🎳
Só lembra de remover esses comentários em inglês daí

2023-05-19 22:20 UTC, Gugonunes commented on LICENSE
> +Copyright (c) 2023 Jeferson Rosa de Souza
🤔 hmmm

2023-05-19 22:20 UTC, Gugonunes commented on manifest.json
> +  "description": "description",
Porque aqui regrediu pro antigo? Acho que pode por "HandMouse" e aquela descrição

2023-05-19 22:20 UTC, Gugonunes commented on manifest.json
> +    "default_title": "extension-title",
Aqui também acho que já pode por o nome

2023-05-23 22:01 UTC, merged